### ISSUE TITLE
complex lookups fail

### ISSUE THREAD

**Issue by zeroem** [matross/mapstache#1]
you can't lookup across multiple maps

**Comment by darkone23** [comment]
created a failing test case:

https://github.com/matross/mapstache/blob/master/test/matross/mapstache_test.clj#L114-L116

**Comment by darkone23** [comment]
I think this is just the logic in the circular lookup detection and not a problem with the map implementation itself, will investigate later

edit: after some initial investigation this is an actual unnecessary circular lookup in the implementation, gotta dig deeper to figure out why

**Comment by zeroem** [comment]
This is the exact issue I'm running into with "fixing" the root bug. Clostache is doing something really weird internally, and I'm trying to understand exactly what it's trying to do.

**Comment by darkone23** [comment]
I'm not sure there is anything we can do to avoid the behavior of clostache.

I'm marking this ticket as closed and using stencil for the tests, maybe we should make a note of recommended mustache engines?
