### ISSUE TITLE
mapstache destroys lazy seqs

### ISSUE THREAD

**Issue by darkone23** [matross/mapstache#2]
When passing a map to mapstache it devours the contents of any lazy seq inside.

``` clj
(mustached {:key (range 3)})
;; => {:key (nil nil nil)}
```

**Comment by darkone23** [comment]
failing test case added: https://github.com/matross/mapstache/commit/d0711e34942515de52e5139cb89d30e73234e320#diff-425fb4ab5d5975e867613250426adfc0R130

**Comment by zeroem** [comment]
Poking at this a little, the problem isn't lazy seqs, it's lists. Vectors support the `get` function, which in turn means I can call:
`(get-in {:key [0 1 2]} [:key 1])`
Lists, however, do not support it, so
`(get-in {:key '(0 1 2)} [:key 1])`
will return `nil`

The simple solution would be to explicitly cast it to a vec before processing, but I have some hesitation in messing with someone else's types

**Comment by zeroem** [comment]
That'll make the test pass, still don't know how I feel about the casting though.

**Comment by darkone23** [comment]
Yaaarrrrggg

``` clj
(mustached (mustached {:a '(1 2 3)}))
;; => {:a (nil nil nil)}
```

**Comment by darkone23** [comment]
Attempt to recursively resolve lists, probably not the prettiest, but it resolves the issues above

https://github.com/matross/mapstache/commit/4d557be79597a414a98500db2d65f35aebc2ef1c

Is there a better way to do this?

**Comment by darkone23** [comment]
I pushed 0.3.1 out with this change for functionality, there is probably a better way to do this in the future.

Closing the ticket for now.
